project to diplom part2
Perminand/java-explore-with-me pull request #4
Opened 2024-09-18 16:17 UTC by Perminand

2024-09-20 16:52 UTC, tomattman requested changes
Привет, коментраииев много, в основном по именам и структуре,

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/common/ConnectToStatServer.java
> +public class ConnectToStatServer {
я не могу понять для чего вообще нужен этот компонент

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/common/GeneralConstants.java
> +public class GeneralConstants {
почему бы просто не назвать Constants

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/controllers/adminApi/CategoryAdminController.java
> +@RequestMapping(value = "/admin", produces = MediaType.APPLICATION_JSON_VALUE)
обычно общую часть выносят в маппинг на уровне контроллера
например этот контроллер обрабатывает все админские категории
и все эндпоинты в этом контроллер начинаются с /admin/categories
так почему бы не вынести это на уровень контроллера, а в методах добавлять только то, что у них отличается

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/controllers/adminApi/CategoryAdminController.java
> +@RequestMapping(value = "/admin", produces = MediaType.APPLICATION_JSON_VALUE)
этот комментарий касается всех контроллеров

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/controllers/adminApi/CategoryAdminController.java
> +package ru.practicum.ewm.main.controllers.adminApi;
в пакете contorollers три подпакета, и в каждом из них есть постфикс api
зачем он здесь?
можно его удалить, и так понятно что в пакете contorllers будут только контроллеры

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/exceptions/ApiError.java
> +public class ApiError {
я бы рекомендовал назвать этот класс хотя бы ApiErrorDto 
как минимум потому что это dto и Error это тип ошибок в джаве и может вызывать путаницу

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/mappers/CategoryMappers.java
> +    public static Category toCategory(CategoryDto categoryDto) {
тут тоже можно улучшить 
зачем давать такие длинные имена методам, если и без этого понятно для чего они
можно оставить toDto и toEntity если надо то toShortDto
все равно методы статические и скорее всего вызов будет таким CategoryMapper.toCategory()
в этом вызове два раза встречается категория

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/mappers/CategoryMappers.java
> +public class CategoryMappers {
я бы рекомендовал называть все в единственном числе, кроме переменных, которые хранят множенственные значения
а классы и пакеты лучше в единственном числе

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/model/category/dto/CategoryDto.java
> +package ru.practicum.ewm.main.model.category.dto;
а dto я бы рекомендовал хранить отдельно от сущностей базы данных, потому что они несут разный функционал, и дто гораздо ближе к уровню контроллеров чем к сущностям базы данных

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/model/markers/Create.java
> +package ru.practicum.ewm.main.model.markers;
почему маркеры в пакете с моделями тоже вопрос

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/model/status/RequestStatus.java
> +package ru.practicum.ewm.main.model.status;
если это статус запроса, то логичнее хранить его в пакете с запросом

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/model/status/State.java
> +package ru.practicum.ewm.main.model.status;
а тут было бы хорошо понимать state чего это, лучше именем, и пакетом тоже
потмоу что таких состояний в одном проекте могут быть десятки

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/service/categories/CategoryServiceImp.java
> +        int startPage = from > 0 ? from / size : 0;
есть подозрение что этот кусочек кода, будет повторяться много где, я бы рекомендовал сделать какой ни будь статический метод в утильном классе, и переиспользовать его везде

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/service/categories/CategoryServiceImp.java
> +    private final Validate validate;
что за класс validate?
validate хорошее имя для метода, ведь методы это действия, класс лучше назвать Validator

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/service/categories/CategoryServiceImp.java
> +        if (eventOptional.isPresent()) {
тут сразу два момента,
1) не понятное имя, хорошее имя не нуждается в описании, лучше назвать по функционалу
2) а зачем вообще создавать переменную строчки 47 - 50 можно заменить на
eventRepository.findByCategoryId(catId).orElseThrow(/*тут создание ошибки, если хочешь не стандартную*/)

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/service/compilations/CompilationServiceImpl.java
> +        Pageable pageable = PageRequest.of(from / size, size);
в сервисе категорий была проверка перед созданием страницы

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/service/event/EventServiceImpl.java
> +        Event event = validate.getEventById(eventId);
этот метод выглядит не очень, из-за наличия такого количества if else я бы рекомендовал поправить это
как по мне самый красиывый способ, сделять это через лямбды, но можно подумать и придумать дургой

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/service/event/EventServiceImpl.java
> +    public List<EventShortDto> getEventsFilter(String text, List<Long> categories, Boolean paid, String rangeStart, String rangeEnd, Boolean onlyAvailable, String sort, Integer from, Integer size) {
по названию метода кажется что должен возвращать какой то фильтр но возвращает писок ивентов

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/service/event/EventServiceImpl.java
> +                .map(EventMappers::toShortDto)
я бы рекомендовал сделать в маппере метода который перегружал бы метод toShortDto принимая в себя список, и уже внутри этого метода проходился бы по списку и для каждого элемента вызывал бы маппер для одного элмента
А то сейчас получается что логика маппинга размазана по разным местам, немного тут немного в маппере

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/service/event/EventServiceImpl.java
> +            List<Long> initiator,
когда так много парметров в методе, можно создать специальную Dto чтобы их передавать и принимать один параметр, это dto

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/validate/Validate.java
> +public class Validate {
Про имя этого класса я уже писал

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/validate/Validate.java
> +    public User getUserById(Long userId) {
то что делает этот метод, это скорее не валидация, а просто чуть усложеннное получение обьекта из базы, поэтому мне кажется не уместно чтобы эти методы были в классе с именем validate 
я рекомендую в каждом сервисе где такой метод нужен, просто добавлять приватный метод которы будет нужен этому классу
да будет дубликация кода, но за то код будет болле структурирован и понятен

А что если у тебя появится еще сотня сущностей базы, на каждую будет тут дополнительны метод?

2024-09-20 16:52 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/validate/Validate.java
> +    public void validateDates(LocalDateTime start, LocalDateTime end) {
единственный метод, который по логике мог бы быть здесь, но лучше попнравить ему имя, чтобы было понятно правило валидирования

2024-09-21 08:43 UTC, Perminand commented on main-service/src/main/java/ru/practicum/ewm/main/controllers/adminApi/CategoryAdminController.java
> +package ru.practicum.ewm.main.controllers.adminApi;
Это сделоно потому что идея не пропускает название private и public

2024-09-21 10:36 UTC, Perminand commented on main-service/src/main/java/ru/practicum/ewm/main/service/categories/CategoryServiceImp.java
> +        if (eventOptional.isPresent()) {
Pltcm наоборот Нужно исключение если Оптионал не пустой

2024-09-22 13:35 UTC, Perminand commented on main-service/src/main/java/ru/practicum/ewm/main/service/event/EventServiceImpl.java
> +        Event event = validate.getEventById(eventId);
Александр. Мои попытки изменить этот метод вызвали только более нагруженное приложение которое начинало запускаться в 1,5 раза дольше. Пожалуйста сообщите действительно ли обязательно нужно изменять этот метод? Какие проблемы решит измененный метод и что даст. Если это действительно обязательно подскажите какую сигнатуру должен содержать ожидаемый метод.
Попытки:
`@Override
    @Transactional
    public EventFullDto update(Long eventId, UpdateEventAdminRequestDto updateRequestDto) {
        Event event = getEventById(eventId);

        LocalDateTime localDateTime;
        if (updateRequestDto.getEventDate() != null) {
            localDateTime = LocalDateTime.parse(
                    updateRequestDto.getEventDate(),
                    Constants.DATE_FORMATTER);
            if (localDateTime.minusHours(1).isBefore(LocalDateTime.now())) {
                throw new ValidationException("Время уже наступило или осталось менее часа до мероприятия");
            }
        }
        
        if (updateRequestDto.getStateAction() != null) {
            if (updateRequestDto.getStateAction().equals(StateAction.PUBLISH_EVENT) && event.getState().equals(EventStatus.PUBLISHED)) {
                throw new DataIntegrityViolationException("Event is already published");
            }
            if (updateRequestDto.getStateAction().equals(StateAction.PUBLISH_EVENT) && event.getState().equals(EventStatus.CANCELED)) {
                throw new DataIntegrityViolationException("Event is canceled");
            }
            if (updateRequestDto.getStateAction().equals(StateAction.REJECT_EVENT) && event.getState().equals(EventStatus.PUBLISHED)) {
                throw new DataIntegrityViolationException("Event is already published");
            }
            if (updateRequestDto.getStateAction().equals(StateAction.REJECT_EVENT)) {
                event.setState(EventStatus.CANCELED);
            } else {
                event.setState(EventStatus.PUBLISHED);
                event.setPublishedOn(LocalDateTime.now().format(Constants.DATE_FORMATTER));
            }
        }

        Utilities.setValueDtoIfNotNull(
                updateRequestDto.getAnnotation(),
                event::setAnnotation);


        Utilities.setValueDtoIfNotNull(
                updateRequestDto.getDescription(),
                event::setDescription);

        Utilities.setNewValueIfNotNull(
                updateRequestDto.getEventDate(),
                event::setEventDate,
                LocalDateTime.parse(updateRequestDto.getEventDate(), Constants.DATE_FORMATTER));

        Utilities.setValueDtoIfNotNull(
                updateRequestDto.getPaid(),
                event::setPaid);

        Utilities.setValueDtoIfNotNull(
                updateRequestDto.getParticipantLimit(),
                event::setParticipantLimit);

        Utilities.setValueDtoIfNotNull(
                updateRequestDto.getRequestModeration(),
                event::setRequestModeration);

        Utilities.setValueDtoIfNotNull(
                updateRequestDto.getTitle(),
                event::setTitle);
        
        if (updateRequestDto.getCategory() != null) {
            event.setCategory(getCategoryById(updateRequestDto.getCategory()));
        }

        if (updateRequestDto.getLocation() != null) {
            Location loc = locationRepository.save(updateRequestDto.getLocation());
            event.setLocation(loc);
        }
        
        if (updateRequestDto.getStateAction() == StateAction.PUBLISH_EVENT) {
            event.setState(EventStatus.PUBLISHED);
            event.setPublishedOn(LocalDateTime.now().format(Constants.DATE_FORMATTER));
        } else if (updateRequestDto.getStateAction() == StateAction.REJECT_EVENT) {
            event.setState(EventStatus.CANCELED);
        }

        eventRepository.save(event);
        return EventMapper.toFullDto(event);
    }`
    
    метод :
    `public static <T> void setValueIfNotNull(T params, Consumer<T> consumer) {
        if (Objects.nonNull(params)) {
            consumer.accept(params);
        }
    }`

2024-09-22 15:58 UTC, tomattman approved these changes
принято

2024-09-22 16:02 UTC, merged